version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: GestionUser
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./GestionUser
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/GestionUser?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JIMDASHBOARD_DATASOURCE_URL: jdbc:mysql://mysql:3306/jimdashboard?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_JIMDASHBOARD_DATASOURCE_USERNAME: root
      SPRING_JIMDASHBOARD_DATASOURCE_PASSWORD: ""
      MAILING_FRONTEND_ACTIVATION_URL: http://localhost:4200/activate-account
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./GestionUserDIM2
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mysql-data:
